# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile',
            field=models.ImageField(upload_to=b''),
        ),
    ]
