# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20160813_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
